/**
 * @spencer-shadley/repo-quality/default-branch-guard (repo-template#440, parent FHR#80)
 *
 * A versioned Git hook that refuses commits on the default branch of a canonical checkout and
 * names the reachable exit (a linked worktree). Linked worktrees and non-default branches are
 * unaffected. It is a hook, never an ACL, read-only attribute or OS lock (code#4094).
 *
 * Install once at adoption or enrollment:
 *   node ./node_modules/@spencer-shadley/repo-quality/default-branch-guard.mjs install
 * Detect drift (missing, outdated or foreign hooks) with `check`.
 */
import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

export const DEFAULT_BRANCH_GUARD_VERSION = 1;
export const DEFAULT_BRANCH_GUARD_MARKER = "repo-quality default-branch-guard";
export const DEFAULT_BRANCH_GUARD_HOOKS = Object.freeze(["pre-commit", "pre-merge-commit"] as const);

export type DefaultBranchGuardHookName = (typeof DEFAULT_BRANCH_GUARD_HOOKS)[number];
export type DefaultBranchGuardHookState = "current" | "outdated" | "missing" | "foreign";

export interface DefaultBranchGuardHookStatus {
  name: DefaultBranchGuardHookName;
  path: string;
  state: DefaultBranchGuardHookState;
  /** Installed guard version when the hook is ours. */
  version?: number;
}

export interface DefaultBranchGuardInspection {
  ok: boolean;
  hooksDir: string;
  expectedVersion: number;
  hooks: DefaultBranchGuardHookStatus[];
}

export interface DefaultBranchGuardInstallReceipt {
  ok: boolean;
  hooksDir: string;
  version: number;
  written: DefaultBranchGuardHookName[];
  unchanged: DefaultBranchGuardHookName[];
  /** Foreign hooks left untouched; the install is incomplete while any remain. */
  refused: DefaultBranchGuardHookName[];
}

export interface DefaultBranchGuardOptions {
  repoRoot: string;
  env?: NodeJS.ProcessEnv;
}

const MARKER_PATTERN = new RegExp(String.raw`${DEFAULT_BRANCH_GUARD_MARKER} v(\d+)\b`);

/** POSIX sh body shared by both hooks. Git for Windows runs hooks through its bundled sh. */
export function renderDefaultBranchGuardHook(): string {
  return `#!/bin/sh
# ${DEFAULT_BRANCH_GUARD_MARKER} v${String(DEFAULT_BRANCH_GUARD_VERSION)} (repo-template#440)
# Generated by @spencer-shadley/repo-quality. Do not edit; reinstall with
#   node ./node_modules/@spencer-shadley/repo-quality/default-branch-guard.mjs install
# Refuses commits on the default branch of a canonical checkout. Linked worktrees,
# other branches and detached HEAD are not affected.
git_dir=$(git rev-parse --git-dir 2>/dev/null) || exit 0
common_dir=$(git rev-parse --git-common-dir 2>/dev/null) || exit 0
[ "$(cd "$git_dir" && pwd -P)" = "$(cd "$common_dir" && pwd -P)" ] || exit 0
branch=$(git symbolic-ref --quiet --short HEAD 2>/dev/null) || exit 0
default_branch=$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null)
default_branch=\${default_branch#origin/}
if [ -z "$default_branch" ]; then
  for candidate in master main; do
    if git show-ref --verify --quiet "refs/remotes/origin/$candidate"; then
      default_branch=$candidate
      break
    fi
  done
fi
[ -n "$default_branch" ] && [ "$branch" = "$default_branch" ] || exit 0
repo_name=$(basename "$(git rev-parse --show-toplevel 2>/dev/null)")
cat >&2 <<GUARD
default-branch-guard: refusing to commit on '$branch', the default branch of this canonical checkout.
The canonical checkout is a reference, not a workspace. Commit from a linked worktree instead:
  git worktree add -b <topic-branch> ../$repo_name-<topic> origin/$default_branch
Fleet hosts: fleet-cli git session-worktree creates the same governed worktree.
GUARD
exit 1
`;
}

function hooksDirFor({ repoRoot, env }: DefaultBranchGuardOptions): string {
  const result = spawnSync("git", ["rev-parse", "--path-format=absolute", "--git-path", "hooks"], {
    cwd: repoRoot,
    env: env ?? process.env,
    encoding: "utf8",
  });
  if (result.status !== 0) {
    throw new Error(`default-branch-guard: ${repoRoot} is not a Git checkout: ${result.stderr.trim()}`);
  }
  return result.stdout.trim();
}

function hookStatus(hooksDir: string, name: DefaultBranchGuardHookName): DefaultBranchGuardHookStatus {
  const hookPath = path.join(hooksDir, name);
  if (!existsSync(hookPath)) return { name, path: hookPath, state: "missing" };
  const text = readFileSync(hookPath, "utf8");
  const match = MARKER_PATTERN.exec(text);
  if (!match) return { name, path: hookPath, state: "foreign" };
  const version = Number(match[1]);
  const current = text === renderDefaultBranchGuardHook();
  return { name, path: hookPath, state: current ? "current" : "outdated", version };
}

export function inspectDefaultBranchGuard(options: DefaultBranchGuardOptions): DefaultBranchGuardInspection {
  const hooksDir = hooksDirFor(options);
  const hooks = DEFAULT_BRANCH_GUARD_HOOKS.map((name) => hookStatus(hooksDir, name));
  return {
    ok: hooks.every((hook) => hook.state === "current"),
    hooksDir,
    expectedVersion: DEFAULT_BRANCH_GUARD_VERSION,
    hooks,
  };
}

/** Write missing or outdated guard hooks. A foreign hook is never overwritten. */
export function installDefaultBranchGuard(options: DefaultBranchGuardOptions): DefaultBranchGuardInstallReceipt {
  const inspection = inspectDefaultBranchGuard(options);
  const receipt: DefaultBranchGuardInstallReceipt = {
    ok: true,
    hooksDir: inspection.hooksDir,
    version: DEFAULT_BRANCH_GUARD_VERSION,
    written: [],
    unchanged: [],
    refused: [],
  };
  mkdirSync(inspection.hooksDir, { recursive: true });
  for (const hook of inspection.hooks) {
    if (hook.state === "current") {
      receipt.unchanged.push(hook.name);
    } else if (hook.state === "foreign") {
      receipt.refused.push(hook.name);
      receipt.ok = false;
    } else {
      writeFileSync(hook.path, renderDefaultBranchGuardHook(), "utf8");
      chmodSync(hook.path, 0o755);
      receipt.written.push(hook.name);
    }
  }
  return receipt;
}

export interface DefaultBranchGuardCliDeps {
  env?: NodeJS.ProcessEnv;
  log?: (line: string) => void;
}

/** CLI: `install|check [--repo <dir>]`. Exit 0 ok, 1 drift/refusal, 2 usage. */
export function main(argv: readonly string[], deps: DefaultBranchGuardCliDeps = {}): number {
  const log = deps.log ?? ((line: string): void => { process.stdout.write(`${line}\n`); });
  const [mode, ...rest] = argv;
  const repoFlag = rest.indexOf("--repo");
  const repoRoot = path.resolve(repoFlag === -1 ? "." : (rest[repoFlag + 1] ?? "."));
  const options: DefaultBranchGuardOptions = { repoRoot, ...(deps.env ? { env: deps.env } : {}) };
  if (mode === "install") {
    const receipt = installDefaultBranchGuard(options);
    log(JSON.stringify(receipt));
    if (!receipt.ok) {
      log(`default-branch-guard: foreign hook(s) left untouched in ${receipt.hooksDir}: ${receipt.refused.join(", ")}. `
        + "Merge the guard into them by hand or move them aside, then rerun install.");
    }
    return receipt.ok ? 0 : 1;
  }
  if (mode === "check") {
    const inspection = inspectDefaultBranchGuard(options);
    log(JSON.stringify(inspection));
    return inspection.ok ? 0 : 1;
  }
  log("usage: default-branch-guard <install|check> [--repo <dir>]");
  return 2;
}
