import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { emitAll, generatedName } from "../tools/emit-repo-quality.ts";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const packageName = "@spencer-shadley/repo-quality";
const packageVersion = "1.12.2";
const deterministicIdentity = {
  GIT_AUTHOR_NAME: "repo-template package materializer",
  GIT_AUTHOR_EMAIL: "repo-template-package@invalid.example",
  GIT_AUTHOR_DATE: "2000-01-01T00:00:00Z",
  GIT_COMMITTER_NAME: "repo-template package materializer",
  GIT_COMMITTER_EMAIL: "repo-template-package@invalid.example",
  GIT_COMMITTER_DATE: "2000-01-01T00:00:00Z",
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function git(args: string[], env: NodeJS.ProcessEnv = process.env): string {
  return execFileSync("git", args, { cwd: root, env, encoding: "utf8" }).trim();
}

/**
 * The published .mjs entrypoints are committed (git consumers run no build) and are also re-emitted
 * here from the checked-out sources, so the artifact tree always carries the freshly generated bytes.
 * The checkout must match the source commit so the emit cannot reflect uncommitted edits.
 */
function treeWithGeneratedEntrypoints(sourceCommit: string): string {
  const sourceTree = git(["rev-parse", `${sourceCommit}:packages/repo-quality`]);
  if (git(["status", "--porcelain", "--", "packages/repo-quality"]) !== "" || git(["rev-parse", "HEAD"]) !== git(["rev-parse", sourceCommit])) {
    throw new TypeError("repo-quality artifacts must be emitted from a clean checkout of the source commit");
  }
  const scratch = mkdtempSync(join(tmpdir(), "repo-quality-index-"));
  const env = { ...process.env, GIT_INDEX_FILE: join(scratch, "index") };
  try {
    git(["read-tree", sourceTree], env);
    for (const [sourceName, bytes] of emitAll()) {
      const blob = execFileSync("git", ["hash-object", "-w", "--stdin"], { cwd: root, input: bytes, encoding: "utf8" }).trim();
      git(["update-index", "--add", "--cacheinfo", `100644,${blob},${generatedName(sourceName)}`], env);
    }
    return git(["write-tree"], env);
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

export function materializeRepoQualityCommit(sourceCommit = "HEAD"): string {
  const tree = treeWithGeneratedEntrypoints(sourceCommit);
  const manifest: unknown = JSON.parse(git(["show", `${sourceCommit}:packages/repo-quality/package.json`]));
  if (!isRecord(manifest)) throw new TypeError("repo-quality source manifest must be a JSON object");
  if (manifest["name"] !== packageName || manifest["version"] !== packageVersion) {
    throw new TypeError(
      `repo-quality source identity mismatch: expected ${packageName}@${packageVersion}, got ${String(manifest["name"])}@${String(manifest["version"])}`,
    );
  }
  const commit = git(
    ["commit-tree", tree, "-m", `${packageName}@${packageVersion}`],
    { ...process.env, ...deterministicIdentity },
  );
  const commitRecord = git(["cat-file", "-p", commit]);
  if (!commitRecord.startsWith(`tree ${tree}\n`) || commitRecord.includes("\nparent ")) {
    throw new TypeError("materialized repo-quality commit must contain the exact package tree with no parent");
  }
  return commit;
}

if (import.meta.main) {
  const [mode, sourceCommit = "HEAD", targetRef = "refs/tags/repo-quality-v1.12.2"] = process.argv.slice(2);
  if (mode !== "print" && mode !== "publish") {
    throw new TypeError("usage: build-repo-quality-npm.ts <print|publish> [source-commit] [target-ref]");
  }
  const artifactCommit = materializeRepoQualityCommit(sourceCommit);
  if (mode === "publish") {
    execFileSync("git", ["push", "origin", `${artifactCommit}:${targetRef}`], { cwd: root, stdio: "inherit" });
  }
  console.log(JSON.stringify({ packageName, packageVersion, sourceCommit, artifactCommit, ...(mode === "publish" && { targetRef }) }));
}
